name: Fix File Permissions

on:
  pull_request:
    branches:
      - main

jobs:
  fix-permissions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set correct file permissions
        run: |
          find . -type f -exec chmod 644 {} \;
          find . -type d -exec chmod 755 {} \;
      - name: Commit permission changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add -A
          git commit -m "Fix file permissions" || echo "No changes to commit"
          git push

