name: GitHub Actions CI
on:
  push:
    branches: master
  pull_request:
  merge_group:
permissions:
  contents: read
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4.2.2
      - name: Set up Ruby
        uses: ruby/setup-ruby@c95ae3725f6ebdd095f2bd19caed7ebc14435ba5 # v1
        with:
          bundler-cache: true
      - name: Set up Node
        uses: actions/setup-node@v4.4.0
      - name: Bootstrap
        run: script/bootstrap
        env:
          SKIP_BUNDLER: true
      - name: Tests
        run: script/test
